name: gepc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - osfclient
  - hydra-core=1.3
  - lightning=2.5
  - tensorboard
  - scipy
  - gillespy2
  - scons
  - tqdm
  - jupyter
  - matplotlib
  - setuptools=81.0
