data:
  # paths
  train_load_path: ???
  valid_load_path: ???
  # camera
  camera_max: 4095.0
  # window
  past_steps: 36
  horizon: 12
  # sampling
  samples_per_cell: 500
  # loader
  batch_size: 128
  num_workers: 0
  shuffle: true
  # seed
  seed: ${seed}
