# @package _global_

defaults:
  - /schema/data@_here_
  - /schema/model@_here_: lstm
  - /schema/objective@_here_
  - /schema/simulator@_here_
  - /schema/trainer@_here_
  - _self_

name: ???
seed: 105

data:
  train_load_path: data/simulate/Style4-Train.pkl
  valid_load_path: data/simulate/Style4-Valid.pkl

simulator:
  data_save_path: null  # not used, explicitly set to null for safety

trainer:
  log_save_fold: data/train-log/${name}
  ckpt_save_fold: data/train-ckpt/${name}
